# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- script: echo Dummy Docker image build
  displayName: 'Build docker image'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      terraform init
      terraform apply -var-file="test.tfvars" -auto-approve
    workingDirectory: 'infra/venkat_terraform'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f aks-store-quickstart.yaml
      kubectl get service store-front --output 'jsonpath={..status.loadBalancer.ingress[0].ip}'
